// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfymO3OaD-m0UfxJWxBx1nrl_j5i-g5Lo',
    appId: '1:770775629622:web:5c8e9b6d15d05fe115bd97',
    messagingSenderId: '770775629622',
    projectId: 'test-1dc4e',
    authDomain: 'test-1dc4e.firebaseapp.com',
    storageBucket: 'test-1dc4e.appspot.com',
    measurementId: 'G-C29JW11G3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTACv3nvXlW9AfVGsleITR9AyxIv8yK3o',
    appId: '1:770775629622:android:2223c0ae66facadb15bd97',
    messagingSenderId: '770775629622',
    projectId: 'test-1dc4e',
    storageBucket: 'test-1dc4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHpH8KvlinmkvGJBTquxZQXOkUiLy-PM',
    appId: '1:770775629622:ios:8bc5337df3e73ce115bd97',
    messagingSenderId: '770775629622',
    projectId: 'test-1dc4e',
    storageBucket: 'test-1dc4e.appspot.com',
    iosClientId: '770775629622-2bi6uic0np4m46m5dhlsipms7t1j7c1b.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
